version: '3'

services:
  cli:
    image: hyperledger/fabric-tools:x86_64-1.1.0
    container_name: cli
    tty: true
    environment:
      - CORE_PEER_TLS_ENABLED=true
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
    working_dir: /opt/ws
    volumes:
      - /var/run/:/host/var/run/
      - ./:/opt/ws
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    networks:
      fabric:
        aliases:
          - cli
  ca_org1:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/093165b2f35172684589320cbf2d25ee7f682e7a1e458ee15859af6a5d918d00_sk
    ports:
      - "7054:7054"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    networks:
      fabric:
        aliases:
          - ca.org1.example.com
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/093165b2f35172684589320cbf2d25ee7f682e7a1e458ee15859af6a5d918d00_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.example.com

  orderer:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    networks:
      fabric:
        aliases:
        - orderer.example.com
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/msp/orderer/msp
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1

  peer0_org1:
    hostname: peer0.org1.example.com
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      fabric:
        aliases:
        - peer0.org1.example.com
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer
      - couchdb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    ports:
      - 5984:5984
    networks:
      fabric:
        aliases:
        - couchdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    environment:
      DB_URL: http://localhost:5984/member_db

  peer1_org1:
    hostname: peer1.org1.example.com
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
       - CORE_LOGGING_PEER=debug
       - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
       - CORE_PEER_ID=peer1.org1.example.com
       - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
       - CORE_PEER_LOCALMSPID=Org1MSP
       - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      fabric:
        aliases:
        - peer1.org1.example.com
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    depends_on:
      - orderer
      - couchdb1

  couchdb1:
    hostname: couchdb1
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    ports:
      - 6984:5984
    networks:
      fabric:
        aliases:
        - couchdb1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    environment:
      DB_URL: http://localhost:6984/member_db

networks:
  fabric:
    external:
      name: fabric





